[package]
name = "ws-common"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
url = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"